stages:
  - test
  - online-test
  - teardown

# Disable GitLab CI's default cache policy of "pull-push"
# https://docs.gitlab.com/ee/ci/yaml/#cache-policy
# https://docs.gitlab.com/ce/ci/caching/index.html#disabling-cache-on-specific-jobs
cache: {}

include:
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/hidden-jobs.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/teardown.yml

variables:
  JULIA_IMAGE: 468665244580.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:1.0
  ONLINE: ""

"1.0 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_0

"1.0 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker  # Version determined by JULIA_IMAGE

"1.1 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_1

"1.1 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_1_1

"Nightly (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_nightly

"Nightly (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_nightly

"Online Tests":
  stage: online-test
  tags:
    - linux
    - docker-build
    - shell-ci
  variables:
    ONLINE: "S3"  # Runs the online S3 tests against AWS
    AWS_STACKNAME: gitlab-ci-runners  # Has the test bucket name for the online S3 tests
  script:
    - source julia-ci export
    - export PATH="$PATH:/usr/local/bin"
    - ./julia-ci test
    - ./julia-ci coverage
  extends: .test_shell_1_0
