stages:
  - test
  - online-test
  - teardown

# Disable GitLab CI's default cache policy of "pull-push"
# https://docs.gitlab.com/ee/ci/yaml/#cache-policy
# https://docs.gitlab.com/ce/ci/caching/index.html#disabling-cache-on-specific-jobs
cache: {}

include:
  - project: infrastructure/gitlab-ci-helper
    file: /templates/hidden-jobs.yml
  - project: infrastructure/gitlab-ci-helper
    file: /templates/teardown.yml

variables:
  ONLINE: ""

"1.0 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_0

"1.0 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_0

"1.1 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_1

"1.1 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_1_1

"Nightly (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_nightly

"Nightly (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker_nightly

"Online Tests":
  stage: online-test
  tags:
    - linux
    - docker-build
    - shell-ci
  variables:
    ONLINE: "S3"  # Runs the online S3 tests against AWS
    AWS_STACKNAME: gitlab-ci-runners  # Has the test bucket name for the online S3 tests
  script:
    - source julia-ci export
    - export PATH="$PATH:/usr/local/bin"
    - ./julia-ci test
    - ./julia-ci coverage
  extends: .test_shell_1_0
