---
# Disable GitLab CI's default cache policy of "pull-push"
# https://docs.gitlab.com/ee/ci/yaml/#cache-policy
# https://docs.gitlab.com/ce/ci/caching/index.html#disabling-cache-on-specific-jobs
cache: {}

include:
  - project: infrastructure/gitlab-ci-helper
    file: /templates/julia.yml

variables:
  # Only include Mac & Linux 64-bit jobs in the job matrix
  platform: "64-bit"
  ONLINE: ""

"Online Tests":
  stage: test
  tags:
    - linux
    - docker-build
    - shell-ci
  variables:
    ONLINE: "S3"  # Runs the online S3 tests against AWS
    AWS_STACKNAME: gitlab-ci-runners  # Has the test bucket name for the online S3 tests
  script:
    - source julia-ci export
    - export PATH="$PATH:/usr/local/bin"
    - ./julia-ci test
    - ./julia-ci coverage
  extends: .test_shell_1_0
