stages:
  - test
  - online-test
  - coverage
  - documentation

# Disable GitLab CI's default cache policy of "pull-push"
# https://docs.gitlab.com/ee/ci/yaml/#cache-policy
# https://docs.gitlab.com/ce/ci/caching/index.html#disabling-cache-on-specific-jobs
cache: {}

include:
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/gitlab-templates/test_templates.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/gitlab-templates/coverage.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/gitlab-templates/documentation.yml

variables:
  JULIA_IMAGE: 468665244580.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:0.6
  ONLINE: ""

"0.6 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_0_6

"0.6 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - docker-ci
  extends: .test_docker

"1.0 (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_1_0

"1.0 (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - shell-ci
    - debian
  extends: .test_shell_1_0

"Nightly (Mac)":
  tags:
    - mac
    - shell-ci
  extends: .test_shell_nightly

"Nightly (Linux, 64-bit)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_nightly

"Online Tests":
  stage: online-test
  tags:
    - ecr
    - linux
    - shell-ci
  variables:
    ONLINE: "S3"  # Runs the online S3 tests against AWS
    AWS_STACKNAME: gitlab-ci-runners  # Has the test bucket name for the online S3 tests
  script:
    - source julia-ci export
    - export PATH="$PATH:/usr/local/bin"
    - unset SSL_CERT_DIR  # https://github.com/JuliaLang/julia/issues/20439
    - ./julia-ci test
    - ./julia-ci coverage
  extends: .test_shell_0_6
